# CI Environment
dist: bionic

# Job Configurations
jobs:
  include:
    - language: python
      python:
        - "3.9"
        - "3.10"
      install:
        - cd backend
        - source .venv/bin/activate
        - pip install -r requirements.txt
        - pip install coveralls
        - gem install coveralls-lcov

      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - sonar-scanner
        - coveralls --merge=../frontend/coverage.json
    - language: node_js
      node_js: 14
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "NFtNmyHKElTw8Z6ySU6FRVgKhkR8NTyRxtZO9Pz/Jry7NKH9nbG2KQX5+DBEYCe2qo4S0jLAa/Q3QVcRbRn46Q7zNJR8l0EN7z7YJzq6A6tJgvGgFdzmLKYLcC2HbmKEAU5uUkOOcr0PlzetQFAgJE5RC922hQEC4yhehbdrk+vm1Yvpe3bMxpvqG1106pjfFfYYlHPthsp34TZDVFDOQOx/hb2JRaa3lOLsc+N0OCNNyi58oWpD8HqS80c5TXlCLp3O0Iil2I2V6oDKR50HNmYhVhayMsQIwXIaporruIJeEpR8aiYu5czrNdr+GDt9DA+YatsXU1xYKQHpVap445PNmT3hxES75uDwf1sgO2vOKcbsoiyY7XcHUUMNLNFjRkzlTcTt3JHADvOruR8GMzY+aPEmjs2K+S+0z56TLMS5+62rqBoPQBvJUTgx3wFl5tCs6xznipkQt2bs45iIxumtsJMIele8gi5LYmH/ZJW8yIA3k1a8xGcI7ZbY1RcKnSBZeE6rlDcBiiUUCdca3d0SOaCOgauFpaCtYgKUO9oFGKPwCzFAIJNLgj1YJDz7hIwaArcLThX88D2PKIm9vKecC/v4xnLTdumKCC2ubvu0L2DmRgvXPeg77Vu0gQWhoULrAZEblZKEZfBS4nPsasP5wQzxeqVk+DreHVWiOd0="
      install:
        - cd frontend
        - yarn install
        - yarn global add coveralls

      script:
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
        - coveralls-lcov -v -n coverage/lcov.info > coverage.json
        - cd .. && sonar-scanner
      secure: "tLPRGSKUI5xIrhfle8B6YGbNRLGpJ83rL2S/eZXcc4FwIxOY+0DGy5VjH4dlRMHGYiqosV4gzubYkDuK4Gw2nLblaxjgB2u7UMkpn9hZLaKpPD0Cx8ofMJNk6h79+xMfH9RsDn/Uit+Ghu2xHaiJQoxan+LkOPEB6+M0AEp65yx0IOTWr9DVYYC08riK8GDc2wsTjc+H5Do7raBJ5Mqw2EUFHVmHlgdqR0i8CrtD9q10thW5r+4hvRRbZHXr5/cbRcioDTqnFRE/9UAGJb225LLMMtCz3lRqF//+A6AE9FKish1UqbOeTlZyKkbLAV3yN7MfE9uah1o5PihL+t+qzGosi6ldxJ0xR1oWmA0l6SonrbN5bITpZgmu49THbodZD7tv2AXLrbqE0a7HCoo7UWi0AiA2kFgSVxnReMuypBTRaX4Et2p7ceFuggoS8RsFmiPoIIleLdzuhTIq1O9hm6koe2OseCQLor3GLHQ8kBsLXCiol6NHZSbHXcHluXl+2lCvLwJnUDhD0XFvFFo61z2z7LuGxt7FXxIAuDgj8T9KtL/v7m7NYTLpjTKiMP+Zck3TteEHxNwd30CNKI0BsJtQkyAFj7DRHrf99oLrG8v+Xhi1x1/0rv7lYMhf12r0iQvEdqxkZIJh8t3Az6zAyr7I2gYFYA75WbzO++07ll4="
