# CI Environment
dist: bionic

# Job Configurations
jobs:
  include:
    - language: node_js
      node_js: 16
      python: "3.9"
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "NFtNmyHKElTw8Z6ySU6FRVgKhkR8NTyRxtZO9Pz/Jry7NKH9nbG2KQX5+DBEYCe2qo4S0jLAa/Q3QVcRbRn46Q7zNJR8l0EN7z7YJzq6A6tJgvGgFdzmLKYLcC2HbmKEAU5uUkOOcr0PlzetQFAgJE5RC922hQEC4yhehbdrk+vm1Yvpe3bMxpvqG1106pjfFfYYlHPthsp34TZDVFDOQOx/hb2JRaa3lOLsc+N0OCNNyi58oWpD8HqS80c5TXlCLp3O0Iil2I2V6oDKR50HNmYhVhayMsQIwXIaporruIJeEpR8aiYu5czrNdr+GDt9DA+YatsXU1xYKQHpVap445PNmT3hxES75uDwf1sgO2vOKcbsoiyY7XcHUUMNLNFjRkzlTcTt3JHADvOruR8GMzY+aPEmjs2K+S+0z56TLMS5+62rqBoPQBvJUTgx3wFl5tCs6xznipkQt2bs45iIxumtsJMIele8gi5LYmH/ZJW8yIA3k1a8xGcI7ZbY1RcKnSBZeE6rlDcBiiUUCdca3d0SOaCOgauFpaCtYgKUO9oFGKPwCzFAIJNLgj1YJDz7hIwaArcLThX88D2PKIm9vKecC/v4xnLTdumKCC2ubvu0L2DmRgvXPeg77Vu0gQWhoULrAZEblZKEZfBS4nPsasP5wQzxeqVk+DreHVWiOd0="
      install:
        - source ~/virtualenv/python3.9/bin/activate
        - cd ./frontend
        - yarn install
        - yarn global add coveralls
        - cd ../backend
        - pip install -r requirements.txt
        - pip install coveralls
        - cd ..
        - gem install coveralls-lcov

      script:
        - cd frontend
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
        - coveralls-lcov -v -n coverage/lcov.info > coverage.json
        - cd ../backend
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - coveralls --merge=../frontend/coverage.json
        - cd .. && sonar-scanner
